[package]
name = "cublas-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Shared config and traits for cuBLAS-rs"
license.workspace = true
repository.workspace = true

[dependencies]
half.workspace = true
cuda-core.workspace = true
thiserror.workspace = true
